version: "3"
services: 
    app:
        build: .
        restart: always
        ports: 
            - 80:80
        volumes: 
            - ./src/:/var/www/html/

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: 
             - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080